"""companies.inn set unique

Revision ID: 3e2c254ca503
Revises: e490c00b14ee
Create Date: 2025-07-11 16:35:02.898000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2c254ca503'
down_revision: Union[str, Sequence[str], None] = 'e490c00b14ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_inn'), table_name='companies')
    op.create_index(op.f('ix_companies_inn'), 'companies', ['inn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_inn'), table_name='companies')
    op.create_index(op.f('ix_companies_inn'), 'companies', ['inn'], unique=False)
    # ### end Alembic commands ###
