"""rename profesion

Revision ID: d0c6ab155665
Revises: 18a87a226583
Create Date: 2025-07-11 09:58:29.694367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0c6ab155665'
down_revision: Union[str, Sequence[str], None] = '18a87a226583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('post', sa.Enum('SALES_MANAGER', 'ROP', name='user_post_enum'), nullable=False))
    op.drop_column('users', 'profession')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profession', postgresql.ENUM('SALES_MANAGER', 'ROP', name='user_post_enum'), autoincrement=False, nullable=False))
    op.drop_column('users', 'post')
    # ### end Alembic commands ###
