"""added revenue

Revision ID: 3d9aaa78104d
Revises: a76b8657ace2
Create Date: 2025-07-05 20:05:31.043352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9aaa78104d'
down_revision: Union[str, Sequence[str], None] = 'a76b8657ace2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('revenue', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'revenue')
    # ### end Alembic commands ###
