"""add index in companies.inn

Revision ID: e490c00b14ee
Revises: 50d96687e893
Create Date: 2025-07-11 15:49:51.362365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e490c00b14ee'
down_revision: Union[str, Sequence[str], None] = '50d96687e893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_inn'), 'companies', ['inn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_inn'), table_name='companies')
    # ### end Alembic commands ###
